
FROM python:3.12-alpine

WORKDIR /app
RUN mkdir -p /work

RUN apk add --no-cache git

RUN pip install --root-user-action=ignore \
    fastapi \
    uvicorn \
    PyJWT \
    requests \
    cryptography

COPY gitsync.py .

CMD ["uvicorn", "gitsync:app", "--host", "0.0.0.0", "--port", "8000"]

# The end.
